name: first_flutter_app
description: A new Flutter application.

# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: 3.0.10
  built_value: 7.0.4
  flutter_spinkit: 4.1.2
  flare_flutter: 2.0.6
  event_bus: 1.1.1
  english_words: ^3.1.0
  shared_preferences: 0.5.3
  path_provider: ^1.3.0
  provider: 4.0.5
  stacked: 1.7.6
  connectivity: 0.4.9
  flutter_cupertino_date_picker: ^1.0.12
  fluttertoast: 7.1.1
  visibility_detector: 0.1.4
  flutter_platform_widgets: ^0.32.4
  flutter_inappwebview: 2.1.0
  webview_flutter: 0.3.21
  flutter_webview_plugin: 0.3.11
  get_it: 4.0.4
  get: 3.10.2
  focus_detector: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  json_serializable: ^3.2.0
  injectable_generator: ^1.0.4
  build_runner: 1.10.1
  freezed: ^0.10.9
  built_value_generator: 7.0.4
  hive_generator: ^0.7.0+2
  pedantic: ^1.9.0
  logger: ^0.9.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true

  # 应用中适用静态资源:
  assets:
    - assets/animations/
    - assets/images/advator.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # 自定义字体和图标
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # 详情插件 https://flutter.dev/custom-fonts/#from-packages
