name: first_flutter_app
description: A new Flutter application.

# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: 3.0.3
  flutter_spinkit: 4.1.2
  transparent_image: ^1.0.0
  fluro: 1.5.1
  event_bus: ^1.1.0
  english_words: ^3.1.0
  shared_preferences: 0.5.3
  path_provider: ^1.3.0
  provider: 4.0.4
  provider_architecture: ^1.0.5
  connectivity: 0.4.8+1
  flutter_cupertino_date_picker: ^1.0.12

  logger: ^0.8.2
  get_it: ^3.1.0
  visibility_detector: 0.1.4
  flutter_platform_widgets: ^0.32.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  build_runner: ^1.0.0
  json_serializable: ^3.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true

  # 应用中适用静态资源:
  assets:
    - assets/images/advator.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # 自定义字体和图标
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # 详情插件 https://flutter.dev/custom-fonts/#from-packages
